name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on:
  push:
  create:

jobs:
  build:
    name: Build wheels
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Install dependencies
        run: |
          brew install cpp-gsl
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheel_${{runner.os}}
          path: |
            dist/
            !dist/**/*.md
          
  publish:
    name: Publish to PyPI and TestPyPI
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download wheel artifact (macOS)
        uses: actions/download-artifact@v2
      - name: ls
        run: ls
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

